import argparse
import shutil
from pathlib import Path
import importlib.resources as pkg_resources

import laser_polio_zamfara

DEFAULT_OUTDIR = "laser_polio_zamfara_data"

# Canonical mapping from filenames → manifest variable names
FILENAME_TO_VAR = {
    "Nigeria_age_pyramid_2024.csv": "age_pyramid",
    "cbr_NGA.json": "cbr_nga",
    "distance_matrix_africa_adm2.h5": "distance_matrix",
    "epi_africa_20250408.h5": "epi_20250408",
    "epi_africa_20250421.h5": "epi_20250421",
    "init_immunity_0.5coverage_january.h5": "immunity_50",
    "init_immunity_0.8coverage_january.h5": "immunity_80",
    "node_lookup.json": "node_lookup",
    "compiled_cbr_pop_ri_sia_underwt_africa.csv": "population",
    "regions.yaml": "regions",
    "shp_africa_low_res.gpkg": "shapefile",
    "sia_scenario_1.csv": "sia_future",
    "sia_historic_schedule.csv": "sia_historic",
}


def extract_data(target_dir: Path):
    """Copy packaged data files to target_dir. Returns list of filenames copied."""
    target_dir.mkdir(parents=True, exist_ok=True)

    data_root = pkg_resources.files(laser_polio_zamfara).joinpath("data")
    copied = []

    for file in data_root.iterdir():
        if file.is_file() and file.name != "manifest.py":
            dest = target_dir / file.name
            with file.open("rb") as src, open(dest, "wb") as dst:
                shutil.copyfileobj(src, dst)
            copied.append(file.name)

    return copied


def write_manifest(copied_files, target_dir: Path):
    """Write manifest.py with canonical variable names and require() helper."""
    manifest_file = target_dir / "manifest.py"

    with open(manifest_file, "w") as f:
        f.write("# Auto-generated by laser_polio_zamfara.bootstrap\n")
        f.write("# DO NOT EDIT BY HAND\n\n")

        f.write("from pathlib import Path\n\n")
        f.write(f"DATA_ROOT = Path({repr(str(target_dir.resolve()))})\n\n")

        f.write("def require(path: Path) -> Path:\n")
        f.write("    if not path.exists():\n")
        f.write("        raise FileNotFoundError(\n")
        f.write("            f\"Missing data file: {path}\\n\"\n")
        f.write("            \"Set LASER_POLIO_DATA to the correct location.\"\n")
        f.write("        )\n")
        f.write("    return path\n\n")

        for filename, var_name in FILENAME_TO_VAR.items():
            if filename in copied_files:
                f.write(f"{var_name} = require(DATA_ROOT / {repr(filename)})\n")

        f.write("\n# Default initial immunity used by run_sim.py\n")
        f.write("init_immunity = immunity_50\n")


def main():
    parser = argparse.ArgumentParser(
        description="Unpack Zamfara public data and write a canonical manifest.py"
    )
    parser.add_argument(
        "--target",
        type=Path,
        default=DEFAULT_OUTDIR,
        help=f"Output directory for unpacked data (default: {DEFAULT_OUTDIR})",
    )

    args = parser.parse_args()

    copied_files = extract_data(args.target)
    write_manifest(copied_files, args.target)

    print(f"Data unpacked to: {args.target.resolve()}")
    print(f"Manifest written to: {(args.target / 'manifest.py').resolve()}")
    print()
    print("To use with laser-polio, set:")
    print(f"    export LASER_POLIO_DATA={args.target.resolve()}")
    print("Or in Python:")
    print(f"    import os; os.environ['LASER_POLIO_DATA'] = {repr(str(args.target.resolve()))}")


if __name__ == "__main__":
    main()
